name: Auto-Close Expired Job Roles

on:
  # Run daily at midnight GMT 
  schedule:
    - cron: '0 0 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  auto-close-jobs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call auto-close API endpoint
        run: |
          echo "Starting auto-close job roles process..."
          
          # Make API call to backend endpoint
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Content-Type: application/json" \
            ${{ secrets.BACKEND_URL }}/jobs/auto-close)
          
          # Extract HTTP status code and body
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)
          
          echo "HTTP Status: $http_code"
          echo "Response: $body"
          
          # Check if request was successful
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Successfully auto-closed expired job roles"
            echo "$body" | jq '.'
          else
            echo "❌ Failed to auto-close job roles"
            echo "$body"
            exit 1
          fi

      - name: Log completion
        if: always()
        run: |
          echo "Auto-close job roles workflow completed at $(date -u)"
